services:
  frontend:
    image: aqaziuog/lms-frontend:2.0.0  # Replace with your Docker Hub username
    pull_policy: always
    ports:
      - "80:80"
    depends_on:
      - backend-flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
